sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.8
- 2.6.6
- 2.7.2
- 3.0.1

gemfile:
  - gemfiles/Gemfile.rails-6.0
  - gemfiles/Gemfile.rails-6.1

env: DATABASE_URL=postgres://postgres@localhost/torque_postgresql_test

before_script:
  - psql -c 'DROP DATABASE IF EXISTS torque_postgresql_test;' -U postgres -h localhost
  - psql -c 'CREATE DATABASE torque_postgresql_test;' -U postgres -h localhost
  - bundle exec rake dump

addons:
  postgresql: '9.6'
  code_climate:
    repo_token: d21c4c9d0d7ba6a27368b8e25edad911eb1daa03202e69fe2bc2e42a3ed21de3
