os: linux
arch:
  - arm64
  - ppc64le
  - s390x

language: ruby
rvm:
  - 2.7.2
  - 3.0.1
  - 3.1.0

gemfile:
  - gemfiles/Gemfile.rails-6.0
  - gemfiles/Gemfile.rails-6.1
  - gemfiles/Gemfile.rails-7.0

cache:
  bundler: true

env:
  global:
    - CC_TEST_REPORTER_ID=d21c4c9d0d7ba6a27368b8e25edad911eb1daa03202e69fe2bc2e42a3ed21de3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql -c 'DROP DATABASE IF EXISTS torque_postgresql_test;' -U travis -p 5433
  - psql -c 'CREATE DATABASE torque_postgresql_test;' -U travis -p 5433
  - bundle exec rake dump

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

addons:
  postgresql: '12'
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
